/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import javax.swing.*;
import java.awt.*;

import javax.swing.*;

import java.awt.event.ActionListener;

/**
 *
 * @author HP
 */
public class EJECUCION extends JFrame {

    private String parte1 = "";
    private String parte2 = "";
    private String parte3 = "";
    private String parte4 = "";

    /**
     * Creates new form EJECUCION
     */
    public EJECUCION() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        resul = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        e2 = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        e3 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("dx");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 224, 17, 17));

        resul.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 291, 360, 45));
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 225, 47, -1));

        jLabel2.setText("X");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 17, 17));

        jLabel3.setText("X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 227, 17, 17));
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 228, 43, -1));
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 205, 42, -1));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 228, 47, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText(")");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 194, 17, 56));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("(");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 207, 17, -1));

        jButton2.setText("SALIR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 310, 120));

        jLabel8.setText("RESULTADO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 268, 115, 17));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton3.setText("Clcular Integral directa");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 210, 200, 40));
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 205, 47, -1));
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 205, 42, -1));

        jLabel7.setText("X");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 228, 17, 17));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 228, 43, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("BORRAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 140, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ii.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 20, 390, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (e1.getText().equals("") && a.getText().equals("")) {
            parte1 = "";

        } else {
            int v1 = Integer.parseInt(e1.getText());
            int v2 = Integer.parseInt(a.getText());
            v1 = v1 + 1;
            

            parte1 = v2 + "( x^" + v1+" ) / "+v1;

        }

        if (e2.getText().equals("") && b.getText().equals("")) {
            parte2 = "";

        } else {
            int v1 = Integer.parseInt(e2.getText());
            int v2 = Integer.parseInt(b.getText());
            v1 = v1 + 1;
           
            if (v2 >= 0) {
              parte2 =" + "+ v2 + "( x^" + v1+" ) / "+v1;
            } else {
                 parte2 = v2 + "( x^" + v1+" ) / "+v1;
            }
           

        }
        if (e3.getText().equals("") && c.getText().equals("")) {
            parte3 = "";

        } else {
            int v1 = Integer.parseInt(e3.getText());
            int v2 = Integer.parseInt(c.getText());
            v1 = v1 + 1;
            if (v2 >= 0) {
              parte3 =" + "+ v2 + "( x^" + v1+" ) / "+v1;
            } else {
                 parte3 = v2 + "( x^" + v1+" ) / "+v1;
            }
            

        }
        if (d.getText().equals("")) {
            parte4 = "";

        } else {
            double resul=Double.parseDouble(d.getText());
            if (resul >= 0) {
               parte4 = " + " + d.getText() + "x";
            } else {
                 parte4 = "  " +d.getText() + "x";
            }
           

        }

        resul.setText(parte1 + " " + parte2 + " " + parte3 + " " + parte4 + " + C");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        a.setText("");
        b.setText("");
        c.setText("");
        d.setText("");
        e1.setText("");
        e2.setText("");
        e3.setText("");
        resul.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EJECUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EJECUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EJECUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EJECUCION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EJECUCION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField resul;
    // End of variables declaration//GEN-END:variables
}
